// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "portfolio-20191101050705-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://portfolio-20191101050705-hostingbucket-dev.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
